//
//  OPMLExporter.swift
//  Reed
//
//  Created by Brent Simmons on 12/22/17.
//  Copyright © 2017 Ranchero Software. All rights reserved.
//

import Foundation

@MainActor
struct OPMLExporter {
    static func OPMLString(with dataStore: DataStore, title: String) -> String {
        let escapedTitle = title.escapingSpecialXMLCharacters
        let openingText =
            """
            <?xml version="1.0" encoding="UTF-8"?>
            <!-- OPML generated by Reed -->
            <opml version="1.1">
            	<head>
            		<title>\(escapedTitle)</title>
            	</head>
            <body>

            """

        let middleText = dataStore.OPMLString(indentLevel: 0)

        let closingText =
            """
            	</body>
            </opml>
            """

        let opml = openingText + middleText + closingText
        return opml
    }
}
