//
//  OPMLFile.swift
//  DataStore
//
//  Created by Maurice Parker on 9/12/19.
//  Copyright © 2019 Ranchero Software, LLC. All rights reserved.
//

import DZFoundation
import Foundation
import RSCore
import RSParser

@MainActor
final class OPMLFile {
    private let fileURL: URL
    private let dataStore: DataStore

    private var isDirty = false {
        didSet {
            queueSaveToDiskIfNeeded()
        }
    }

    private let saveQueue = CoalescingQueue(name: "Save Queue", interval: 0.5)

    init(filename: String, dataStore: DataStore) {
        self.fileURL = URL(fileURLWithPath: filename)
        self.dataStore = dataStore
    }

    func markAsDirty() {
        self.isDirty = true
    }

    func load() {
        guard let fileData = opmlFileData(), let opmlItems = parsedOPMLItems(fileData: fileData) else {
            return
        }

        BatchUpdate.shared.perform {
            self.dataStore.loadOPMLItems(opmlItems)
        }
    }

    func save() {
        guard !self.dataStore.isDeleted else { return }
        let opmlDocumentString = opmlDocument()

        do {
            try opmlDocumentString.write(to: self.fileURL, atomically: true, encoding: .utf8)
        } catch let error as NSError {
            DZLog("OPML save to disk failed: \(error.localizedDescription)")
        }
    }
}

extension OPMLFile {
    private func queueSaveToDiskIfNeeded() {
        if Thread.isMainThread {
            MainActor.assumeIsolated {
                self.saveQueue.add(self, #selector(self.saveToDiskIfNeeded))
            }
        } else {
            Task { @MainActor in
                self.saveQueue.add(self, #selector(self.saveToDiskIfNeeded))
            }
        }
    }

    @objc
    private func saveToDiskIfNeeded() {
        if self.isDirty {
            self.isDirty = false
            self.save()
        }
    }

    private func opmlFileData() -> Data? {
        var fileData: Data? = nil

        do {
            fileData = try Data(contentsOf: self.fileURL)
        } catch {
            DZLog("OPML read from disk failed: \(error.localizedDescription)")
        }

        return fileData
    }

    private func parsedOPMLItems(fileData: Data) -> [RSOPMLItem]? {
        let parserData = ParserData(url: fileURL.absoluteString, data: fileData)
        var opmlDocument: RSOPMLDocument?

        do {
            opmlDocument = try RSOPMLParser.parseOPML(with: parserData)
        } catch {
            DZLog("OPML import failed: \(error.localizedDescription)")
            return nil
        }

        return opmlDocument?.children
    }

    private func opmlDocument() -> String {
        let escapedTitle = self.dataStore.nameForDisplay.escapingSpecialXMLCharacters
        let openingText =
            """
            <?xml version="1.0" encoding="UTF-8"?>
            <!-- OPML generated by NetNewsWire -->
            <opml version="1.1">
            <head>
            <title>\(escapedTitle)</title>
            </head>
            <body>

            """

        let middleText = self.dataStore.OPMLString(indentLevel: 0, allowCustomAttributes: true)

        let closingText =
            """
            	</body>
            </opml>
            """

        let opml = openingText + middleText + closingText
        return opml
    }
}
